add_item:
  description: Adds an item to the shopping list.
  fields:
    name:
      description: The name of the item to add.
      example: Beer
complete_item:
  description: Marks an item as completed in the shopping list. It does not remove the item.
  fields:
    name:
      description: The name of the item to mark as completed.
      example: Beer
clear_item:
  description: Removes an item from the shopping list.
  fields:
    name:
      description: The name of the item to delete.
      example: Beer
